baseURL: "https://liu-chao.site"  # Added https://
title: Chao Liu
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

# RSS Configuration - Only for Posts section
outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
    - RSS  # This enables RSS for sections like /posts/

# RSS Feed Settings
rssLimit: 20  # Number of items in RSS feed

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 2
        - name: Posts
          url: posts/
          weight: 2
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 2 
        - name: Publications
          url: publications/
          weight: 2
        - name: Tags
          url: tags/
          weight: 3

params:
    description: "I am an Associate Professor of Psychology at Cedarville University. My teaching and research interests revolve around quantitative methodologies. I am a Christ follower, a husband, and a father of two."
    author: Chao Liu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006" 
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["posts"]  # Only posts will be included in main content feeds
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    ShowPostTags: true
    UseHugoToc: true
    comments: true
    disqusShortname: "liu-chao.site"
    math: true
    
    profileMode:
          enabled: true
          title: Chao Liu
          subtitle: >
            Associate Professor of Psychology@<a href="https://www.cedarville.edu/" style="color: blue;">Cedarville</a>
            

            Christ follower
            

            Quantitative Researcher, husband, and father
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Chao Liu
          buttons:
            - name: About
              url: about/
              weight: 2
            - name: Posts
              url: posts/
              weight: 4
            - name: Papers
              url: papers/
              weight: 2
            - name: Projects
              url: projects/
              weight: 2 
            - name: Publications
              url: publications/
              weight: 2

    socialIcons:
        - name: CV
          url: cv_5-5.pdf
        - name: Email
          url: mailto:chaoliu@cedarville.edu
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=7Mo7trwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/chaoliu-cl
        - name: X
          url: https://x.com/ChaoLiu77600168
        - name: linkedin
          url: https://www.linkedin.com/in/chao-liu-1056663b/
        - name: RSS
          url: posts/index.xml

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Chao Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2